/**
 * One injected stylesheet: web client plugins are served as a single bundle.
 * Class names use the plugin prefix to avoid collisions in the assembled app.
 */
/** Stable style id; idempotent across HMR re-runs. */
export declare const STYLE_ID = "dsh-prompt-rail-style";
/**
 * Visual treatment for the compact, enlarged-hit-area message rail. User
 * marks are light 8×3px lines; assistant marks are shorter and dimmer. Hover
 * or focus grows the current mark to a 28px dark bar, tapers neighbors, and
 * reveals a preview bubble with the message text.
 */
export declare const cssText = "\n.dsh_messageJumpRail_nav {\n  position: sticky;\n  z-index: 9;\n  top: 50%;\n  left: 8px;\n  width: 56px;\n  height: 0;\n  display: flex;\n  flex-direction: column;\n  gap: 0;\n  align-items: flex-start;\n  pointer-events: none;\n}\n.dsh_messageJumpRail_items {\n  display: flex;\n  flex-direction: column;\n  width: 100%;\n  transform: translateY(-50%);\n  pointer-events: none;\n}\n.dsh_messageJumpRail_item {\n  position: relative;\n  display: flex;\n  align-items: center;\n  justify-content: flex-start;\n  width: 56px;\n  height: 10px;\n  flex: 0 0 10px;\n  padding: 0;\n  border: 0;\n  background: transparent;\n  cursor: pointer;\n  pointer-events: auto;\n}\n.dsh_messageJumpRail_mark {\n  display: block;\n  width: 8px;\n  height: 3px;\n  border-radius: 2px;\n  background: var(--dsw-alias-label-tertiary);\n  opacity: 0.55;\n  transition: width 120ms ease, opacity 120ms ease;\n}\n.dsh_messageJumpRail_item[data-kind='assistant'] .dsh_messageJumpRail_mark {\n  width: 4px;\n  height: 2px;\n  opacity: 0.35;\n}\n.dsh_messageJumpRail_item[data-distance='0'] .dsh_messageJumpRail_mark {\n  width: 28px;\n  background: var(--dsw-alias-label-primary);\n  opacity: 0.9;\n}\n.dsh_messageJumpRail_item[data-kind='assistant'][data-distance='0'] .dsh_messageJumpRail_mark {\n  width: 20px;\n  opacity: 0.8;\n}\n.dsh_messageJumpRail_item[data-distance='1'] .dsh_messageJumpRail_mark {\n  width: 20px;\n}\n.dsh_messageJumpRail_item[data-kind='assistant'][data-distance='1'] .dsh_messageJumpRail_mark {\n  width: 12px;\n}\n.dsh_messageJumpRail_item[data-distance='2'] .dsh_messageJumpRail_mark {\n  width: 14px;\n}\n.dsh_messageJumpRail_item[data-distance='3'] .dsh_messageJumpRail_mark {\n  width: 10px;\n}\n.dsh_messageJumpRail_item[data-selected] .dsh_messageJumpRail_mark {\n  background: var(--dsw-alias-brand-primary);\n  opacity: 1;\n}\n.dsh_messageJumpRail_preview {\n  display: none;\n  position: absolute;\n  left: calc(100% + 10px);\n  top: 50%;\n  transform: translateY(-50%);\n  max-width: 340px;\n  min-width: 160px;\n  padding: 8px 10px;\n  border-radius: 8px;\n  border: 1px solid var(--dsw-alias-border-l1);\n  background: var(--dsw-alias-bg-overlay);\n  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2);\n  color: var(--dsw-alias-label-secondary);\n  font-size: 12px;\n  line-height: 18px;\n  white-space: pre-wrap;\n  word-break: break-word;\n  pointer-events: none;\n}\n.dsh_messageJumpRail_item[data-preview-active] .dsh_messageJumpRail_preview {\n  display: -webkit-box;\n  -webkit-line-clamp: 4;\n  -webkit-box-orient: vertical;\n  overflow: hidden;\n}\n.dsh_messageJumpRail_previewKind {\n  display: block;\n  color: var(--dsw-alias-label-tertiary);\n  font-size: 11px;\n  line-height: 16px;\n  margin-bottom: 2px;\n}\n";
/** Inject (or refresh) the stylesheet once; idempotent. */
export declare function adoptStyles(): void;
